### ISSUE TITLE
What version should I download for the DS1821+?

### ISSUE THREAD

**Issue by fabiosirna** [runfalk/synology-wireguard#107]
I want to try this package but not sure which version will fit my DS1821+.
Any help is greatly appreciated.

**Comment by ben-ba** [comment]
From the readme, this link is provided;

https://kb.synology.com/en-global/DSM/tutorial/What_kind_of_CPU_does_my_NAS_have

so it is: V1000 - it is in included in the toolchain but have to build yourself, see instructions on the readme.

**Comment by RyanWor** [comment]
Did you ever figure this out? I have multiple DS1821+ and struggling to get wireguard installed. I tried to build per the readme and get the following error 
`[V1000] is not available platform.`

**Comment by RyanWor** [comment]
Alright I got it figured out so figured I would leave this here for others just in case. Not only did I have V1000 when I needed v1000 there was some issues due to last years LE cert expiry that I had to modify the Makefile to get a successful compile: 

In my Ubuntu 20.04 VM and run the following commands as root (sudo -s):

git clone https://github.com/runfalk/synology-w...
cd synology-wireguard
git fetch origin pull/71/head:DSM7.0
git checkout DSM7.0
sed -i 's/wget\ /wget \-\-no\-check\-certificate\ /g' Makefile
docker build -t synobuild . (there is a space then a period at the end of this command)
mkdir artifacts
docker run --rm --privileged --env PACKAGE_ARCH=v1000 --env DSM_VER=7.0 -v $(pwd)/artifacts:/result_spk synobuild

Manually install the resulting spk in artifacts folder on DS1821+ via Manual Install in Packae Center (uncheck to disable run after install)

Then SSH into DS1821+ and run the following commands as root (sudo -s):

/var/packages/WireGuard/scripts/start
