### ISSUE TITLE
WireGuard-rtd1296-1.0.20200401.spk has  v1.0.20200319 binary

### ISSUE THREAD

**Issue by mrutyunjay-patel** [runfalk/synology-wireguard#43]
hi ,
after installation from Release  WireGuard-rtd1296-1.0.20200401.spk
Version of binary is shows as follows  
` wg --version`  
`wireguard-tools v1.0.20200319 - https://git.zx2c4.com/wireguard-tools/ `

pre-compiled package source : https://github.com/runfalk/synology-wireguard/releases

filename : WireGuard-rtd1296-1.0.20200401.spk**

**Comment by runfalk** [comment]
Hi,

This is expected since the userland tools actually use separate versions. You can see here (https://git.zx2c4.com/wireguard-tools/refs/) that there is no 20200401 version of wireguard-tools. The kernel module itself should be the correct version.

I'll close this for now, let me know if it should be reopened.
