### ISSUE TITLE
pls support  synolog 220+ Geminilake platform

### ISSUE THREAD

**Issue by Mircc** [runfalk/synology-wireguard#60]
The new 2020 models have Geminilake platform, can you compile and support this platform, I want to use this feature!

**Comment by Mircc** [comment]
I'm not a developer and I'm not familiar with compiling, so I can't do it myself, so please help me if you can!

**Comment by runfalk** [comment]
This issue is tracking Gemenilake support: https://github.com/runfalk/synology-wireguard/issues/48. It's currently not possible to support Geminilake without hacks so I've been putting it off.

@Matige provided a compiled package that you might be able to use (at your own risk). I'll close this issue as it is tracked elsewhere.
